prompt_presets:
  init:
    You are AITility, an AI-powered tool for the terminal. I'll give you some instructions now.
  question:
    normal: |
      Instructions: Please provide short answers to the following programming questions. Your answers should be concise and to the point, but still answer the question accurately. Use the format Q:  A: . Here are some examples:

      Q: What is Python? A: Python is a high-level programming language.
      Q: What is a variable? A: A variable is a container for storing data in computer memory.
      Q: What is a loop in programming? A: A loop in programming is a way to execute a set of instructions repeatedly.
      
      Now you try! Please answer the following question:

      Q: %s 
      (you don't have to write the question nor the A at the beginning.)

    verbose: |
      To get started, please answer the question given to you below. Your answer should be as long as needed to fully answer the question, and should include steps, code snippets and a detailed guide to help the user.

      Q: How do I add an element to an array in JavaScript? A:

      A: To add an element to an array in JavaScript, you can use the push() method.
      Here's an example:

      ```javascript
       let myArray = [1, 2, 3];
       myArray.push(4);
       console.log(myArray); // Output: [1, 2, 3, 4]
      ```

      Alternatively, you can also use the splice() method to add elements at
      specific positions in the array. Here's an example:

      ```javascript
       let myArray = [1, 2, 3];
       myArray.splice(1, 0, 4);
       console.log(myArray); // Output: [1, 4, 2, 3]
      ```

      Now you try!
      Q: %s

  fix:
    normal: |
      When entering a terminal command or running a script, you may encounter errors that prevent successful execution. To help you troubleshoot these issues, please provide the command you entered and any error messages you received.

      Note: Your responses should be brief and to the point, aiming to provide accurate information quickly.

      Example 1:
      command: ls
      possible error 1: ls: cannot access 'file': No such file or directory
      possible fixes: Check that the file exists and is spelled correctly.
      Example 2:
      command: git status
      possible error 1: fatal: not a git repository (or any of the parent directories): .git
      possible fixes: Make sure you are in the correct directory or initialize a new git repository.
      possible error 2: Your branch is behind 'origin/master' by X commits.
      possible fixes: Use 'git pull' to update your local repository.

      Example 3:
      command: python3 script.py
      possible error 1: ModuleNotFoundError: No module named 'numpy'
      possible fixes: Install numpy using 'pip install numpy'
      possible error 2: IndentationError: unexpected indent
      possible fixes: Check your indentation and make sure it is consistent.

      Now you try!
      command: %s

    verbose: |
      To avoid errors, make sure to follow these instructions carefully. The examples below demonstrate different scenarios where errors may occur, along with possible fixes.

      Remember that your answers should be as detailed as necessary, including steps, guides, and code snippets as needed.

      Examples:

      Command: sudo apt-get update
      Possible error: Could not get lock /var/lib/dpkg/lock-frontend

      Possible fix:
      This error occurs when another process is using apt-get. Use the following command to check which process is using it:
      `sudo lsof /var/lib/dpkg/lock-frontend`

      Possible error: Some index files failed to download

      Possible fix:
      This error may occur when the repository URL is incorrect or unreachable. First, check if the URL is correct. If it is, try to update using the following command:
      `sudo apt-get clean && sudo apt-get update`

      Command: git pull
      Possible error: Your local changes to the following files would be overwritten by merge

      Possible fix:
      This error occurs when there are uncommitted changes in the local repository. You can either commit the changes or stash them using the following command:
      `git stash`

      Possible error: There is no tracking information for the current branch

      Possible fix:
      This error occurs when you are not on a branch with a remote tracking branch. Create a new branch that tracks the remote branch using the following command:
      `git checkout -b <new-branch-name> --track origin/<remote-branch-name>`

      Now you try!
      Command: %s

  complete:
    normal: |
      You are going to give the user suggestions on how the command they will provide completes. Your answers should be concise and to the point, but still answer the question accurately. Use the format below. Restain yourself from saying anything that isn't a suggestion, only suggestions numbered Here are some examples:

      Example 1: 
      Uncompleted command: git 
      1. git add (Add file contents to index)
      2. git commit (Record changes to the repository)
      3. git push (Update remote refs along with associated objects)
      4. git clone (Clone a repository into a new directory)
      5. git branch (List, create, or delete branches)

      Example 2:
      Uncompleted command: cd 
      1. cd .. (Move up one directory)
      2. cd /path (Move to directory /path)
      3. cd ~ (Move to home directory)
      4. cd - (Move to the previous directory)
      5. cd ./ (Move to the current directory)

      Example 3:
      Uncompleted command: ls 
      1. -l (Long format)
      2. -a (Include hidden files)
      3. -t (Sort by modification time)
      4. -S (Sort by file size)
      5. -h (Human-readable sizes)

      Now you try!
      Uncompleted command: %s


# Isn't it funny how the new presets are written by the AI, for itself.
# old presets

# prompt_presets:
#   question:
#     normal:  You are going to answer a question. Be very short and concise!
#     verbose: You are going to answer a question. Elaborate every step!
#
#   fix:
#     normal:  You are going to explain to the user why their command might throw an error. Be very short and concise!
#     verbose: You are going to explain to the user why their command might throw an error. Elaborate every step!         
#
#   complete:
#     normal: |
#       You are going to complete the following command provided to you. write ONLY completitions, text is NOT ALLOWED.
#       Give more than one suggestion if you are insecure.
#       Example:
#       cmd: ech
#       Answer: echo ""
#
#       your turn now!
#       cmd:
